### ISSUE TITLE
Is it possible to change/update an existing event's alarm/reminder?

### ISSUE THREAD

**Issue by jsochurek** [wmcmahan/react-native-calendar-events#87]
Hi, great package, I am having some trouble changing the alarm/reminder on an existing event.  I set it the first time, and it works fine, then i update the event with the same data but the alarms different, and the reminder stays the same.  Every other field appears to update accordingly. Thoughts? Has anyone been able to accomplish this and I'm just missing something?

Thanks

**Comment by wmcmahan** [comment]
Hi @jsochurek, is this issue for iOS, Android or both?

**Comment by jsochurek** [comment]
I've currently only tested on Android thus far.  some code for context:

`let settings = {
        notes: appointment.title,
        description: appointment.title,
        startDate: appointment.datetime.toISOString(),
        endDate: endDate.toISOString(),
        calendar: ["Calendar"]
      };
      if (appointment.location != null) {
        settings["location"] = this.context.lassieDataInterop.Campus().GetDataSuite(appointment.location).Name;
      }
      if (appointment.calendarID != null) {
        settings["id"] = appointment.calendarID;
      }
      if (appointment.reminder !== appointment.datetime) {
        // We have a reminder
        let num: number = moment(appointment.datetime).diff(moment(appointment.reminder), "minutes");
        settings["alarms"] = [{date: -num}];
      }
      else {
        settings["alarms"] = [];
      }
      console.log("saving or editing calendar event", settings);
      RNCalendarEvents.saveEvent(appointment.title, settings)
      .then(id => {
        appointment.calendarID = id.toString();
        this.context.lassieDataInterop.AddAppointment(appointment);
        this.updateAppointments();
      }).catch(error => console.log("Save Event Error: ", error));
    }`

Every other field will update (title, location, date/time)

**Comment by wmcmahan** [comment]
Thanks @jsochurek, it does look like there is an issue with updating existing alarms in Android. I will take a look and fix that soon.

**Comment by jsochurek** [comment]
@wmcmahan thanks!

**Comment by wmcmahan** [comment]
@jsochurek, I've pushed changes into master that should allow for alarms to be updated/replaced. Also, the alarms are now returned from the resolved promise.

**Comment by jsochurek** [comment]
@wmcmahan thanks for the quick turnaround!

I'm still on 1.4.1 (not yet on RN 0.47), should this code work just as well? The diff between the two files appears to be all from this commit, not from any previous 1.4.2 commits

**Comment by wmcmahan** [comment]
The latest changes currently in master support RN 0.47+. The only real change for supporting for RN 0.47 is in `CalendarEventsPackage.java` - [diff](https://github.com/wmcmahan/react-native-calendar-events/compare/83ec99a2dd088b64763c09d67122f0cbddd7a3b3...master).

**Comment by MariShielaFurio** [comment]
Hi, updating alarm in android still happening to me. Using android emulator Pixel3 Android 9 API 28 and Pixel Android 10 API 29. 

I hope someone can help me. Thanks!!
